server:
  port: 8881
spring:
  application:
    name: spring-cloud-zull-server
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka/

# zuul网关其底层使用ribbon来实现请求的路由，并内置Hystrix，可选择性提供网关fallback逻辑。
# 使用zuul的时候，并不推荐使用Feign作为application client端的开发实现。
# 毕竟Feign技术是对ribbon的再封装，使用Feign本身会提高通讯消耗，降低通讯效率，
# 只在服务相互调用的时候使用Feign来简化代码开发就够了。而且商业开发中，
# 使用Ribbon+RestTemplate来开发的比例更高。
zuul:
  routes:
    users: # key结构 ： zuul.routes.customName.path=xxx
      path: /u/** #如果只配置path，不配置serviceId。则customName相当于服务名称。
      serviceId: users # service id pattern 通过服务名称路由
  # 配置不被zuul管理的服务列表。多个服务名称使用逗号','分隔。
  # 配置的服务将不被zuul代理。
  #此方式相当于给所有新发现的服务默认排除zuul网关访问方式，只有配置了路由网关的服务才可以通过zuul网关访问
#  ignored-services: *
  # 通配方式配置排除网关代理路径。所有符合ignored-patterns的请求路径都不被zuul网关代理。
  ignored-patterns: /u/**
  # 配置请求路径前缀，所有基于此前缀的请求都由zuul网关提供代理
  # 使用服务名称匹配方式配置请求路径规则。
  # 这里的配置将为：http://ip:port/api/u/**的请求提供zuul网关代理，可以将要访问服务进行前缀分类。
  # 并将请求路由到服务eureka-application-service中。
  prefix: /api