server:
  port: 8001
spring:
  application:
    name: order-server
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka/
# 在被监控服务上添加暴露端点
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream