server:
  port: 8003
spring:
  application:
    name: openFeign-order-client
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8888/eureka
  instance:
    hostname: 127.0.0.1
feign:
  hystrix:
    enabled: true # fegin默认关闭hystrix服务
# 在被监控服务上添加暴露端点
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream